### ISSUE TITLE
can it work with Jupyterlab-3.0.0rc1 ?

### ISSUE THREAD

**Issue by stonebig** [ianhi/mpl-interactions#118]
trying to make jupyterlab-3 working, I have issues with ipympl, or matplotlib widgets.

maybe mpl-interactions could smooth the problem

**Comment by ianhi** [comment]
Unfortunately I don't think so. I have ipympl as a dependency. Though widgets are an important enough part of my workflow that as a soon as there is a guide for updating widgets to jlab3 I will use it to update ipympl (unless someone beats me to it). I think the reason ipywidgets proper works is because one of the jlab core devs updated it as a sort of test case for updating widgets to the new system.But the knowledge of how to do that hasn't totally disseminated to the rest of us yet.

**Comment by stonebig** [comment]
yes, it just fails in strange ways:
- bqplot and pydeck don't bother jupyterlab-3 (that ignores them)
- ipympl and ipyleaflet do bother jupyterlab, so I'll remove them, and so  from the Jupyter Classic notebook, for now

**Comment by ianhi** [comment]
Closing as there is a PR in ipympl that will enable it working on jlab 3
https://github.com/matplotlib/ipympl/pull/272
