### ISSUE TITLE
Bug in interactive_axhline

### ISSUE THREAD

**Issue by snowtechblog** [ianhi/mpl-interactions#173]
Error message when using `interactive_axhline`:
`y, ec = prep_scalar(x)`
`NameError: name 'x' is not defined`

Line 810 in `./mpl_interactions/pyplot.py` should be something like that:
`    y, ec, arg = prep_scalar(y, 'y')`
instead of:
`    y, ec = prep_scalar(x)`

**Comment by ianhi** [comment]
Yup good catch! I must've missed that when I updated axvline. Would you like to make a PR fixing this?  I'm happy to as well but since you found the bug and the fix I'd love for you to have credit.

Essentially the version in axhline should mirror whats in axvline: https://github.com/ianhi/mpl-interactions/blob/12ffb56735189e10f6e0549fc590c23ad40a1ece/mpl_interactions/pyplot.py#L909-L911

**Comment by snowtechblog** [comment]
No, please go ahead - you know how to fix these things much more quickly.
Thanks!

BTW: the interactive_plot replots the full line instead of replacing just
the ydata with line.set_ydata. Don't know if this would be good to
implement, since a replot resets a potential user chosen zoom.

Am Do., 25. März 2021 um 23:49 Uhr schrieb Ian Hunt-Isaak <
***@***.***>:

**Comment by ianhi** [comment]
> BTW: the interactive_plot replots the full line instead of replacing just
the ydata with line.set_ydata. Don't know if this would be good to
implement, since a replot resets a potential user chosen zoom.

It shouldn't be replotting the entire line - do you have some example code demonstrating the issue?  The intended behavior is to use `set_data` when both `x` and `y` are provided as functions as here:
https://github.com/ianhi/mpl-interactions/blob/12ffb56735189e10f6e0549fc590c23ad40a1ece/mpl_interactions/pyplot.py#L167-L168

but to use `set_ydata` when only `y` is a function:

https://github.com/ianhi/mpl-interactions/blob/12ffb56735189e10f6e0549fc590c23ad40a1ece/mpl_interactions/pyplot.py#L182-L187


I'll give you that it's a rough situation where currently mpl-interactions always overrides a user chosen zoom. I think that this was ultimately a poor design decision that I made early on and hope to change it someday, but I haven't had the time/it hasn't bothered me enough to do it yet. I do think that it is a bug though: https://github.com/ianhi/mpl-interactions/issues/85

**Comment by ianhi** [comment]
Should be fixed in version `0.17.5` which should be on pypi as soon as https://github.com/ianhi/mpl-interactions/actions/runs/688537139 finishes. 

Thanks again for the report!

**Comment by snowtechblog** [comment]
> It shouldn't be replotting the entire line - do you have some example code demonstrating the issue? The intended behavior is to use `set_data` when both `x` and `y` are provided as functions as here:

You are absolutely right, the code replaces the line data... I tried to mimic an `axhline` equivalent with `iplt.plot`, and what caused a viewpoint reset was the input argument `ylim='stretch'` and `xlim='stretch'` together with the default axes property `ax.autoscale(enable=True)`. With both limits set to `auto` and `ax.autoscale(enable=False)` yield the behavior of preserving the current zoom (though the wording seems a bit weird: set auto on one side and disable it on the other...)

Anyway, thanks for fixing axhline in the new version - a much more sensible way for a horizontal line ,-)

MWE with resetting zoom and preserving zoom level:
```
import matplotlib as mpl
mpl.use('QT5Agg')
import matplotlib.pyplot as plt
import mpl_interactions as mpl_i

no_zoom_reset = True # switch to False to see zoom to reset

fig, ax = plt.subplots()
plt.subplots_adjust(bottom=.25)
axfreq = plt.axes([0.25, 0.1, 0.65, 0.03])
slider = mpl.widgets.Slider(axfreq,label='freq', valmin=.05, valmax = 10, valinit=5)

def hline_data(x, val):
    return [y*0+val for y in x]

if no_zoom_reset:
    controls = mpl_i.interactive_plot([5, 10], hline_data, val=slider, ax=ax, xlim='auto')
    ax.autoscale(enable=False)
else:
    controls = mpl_i.interactive_plot([5, 10], hline_data, val=slider, ax=ax)

plt.show()

```

**Comment by snowtechblog** [comment]
Sorry bother you again... the `kwargs_popper` in `interactive_axhline` needs to be called before the `prep_scalar`

move:
    ```
kwargs, line_kwargs = kwarg_popper(kwargs, Line2D_kwargs_list)
    line_kwargs.pop("transform", None)  # transform is not a valid kwarg for ax{v,h}line
```
from lines 821-822 to 806

**Comment by ianhi** [comment]
> Sorry bother you again... 

not at all! If anything thank you for continuing to do so

> the kwargs_popper in interactive_axhline needs to be called before the prep_scalar

Oh yeah that would make sense. Did this cause a bug for you? I tried it out using this code and it worked fine:
```python
import matplotlib.pyplot as plt

from mpl_interactions import *
fig, ax = plt.subplots()
def y(heck):
    return heck
controls = interactive_axhline(y, heck=(0,1))
```


Though I agree it odes make more sense to have earlier in the function.


> viewpoint reset was the input argument ylim='stretch' and xlim='stretch' together with the default axes property ax.autoscale(enable=True). With both limits set to auto and ax.autoscale(enable=False) yield the behavior of preserving the current zoom (though the wording seems a bit weird: set auto on one side and disable it on the other...). 


All that view rescaling is such a mess :( It's existed since literally the `initial commit` when this library was a single function for a specific problem I had where it made sense to be overly assertive with view scaling https://github.com/ianhi/mpl-interactions/blob/d1b99e344ad8e05644131cb027e49d111b8959f0/jupyter_jukebox/jupyter_jukebox.py#L59-L65 


Do you have an suggestions on ways to change the behavior to be more intuitive or easier to use for you? If you do lets open a new issue and discuss it there.



> Maybe, could be a note in the documentation somewhere.

Totally! Currently there is very limited documentation here https://mpl-interactions.readthedocs.io/en/stable/examples/Usage-Guide.html#Axis-scaling

The trouble is that it's getting ever more difficult for me to write documentation as I become ever more disconnected from being a new user of this library. So I will give it a go but any suggestions you have for what would have made it easier for the you from yesterday to understand would be totally great.

**Comment by ianhi** [comment]
`kwarg_popper` is moved to the correct place in version `0.17.6`. 

---

If you're able to share what you're making I'd love to see it! It's very mysterious to me how other people are using this library. Which makes it difficult to know what parts more need improvement - plus I always love seeing fun plots. Understand if you'd prefer not to though

**Comment by snowtechblog** [comment]
> Did this cause a bug for you?

Yes, I received a bug when setting line width of the hline. With your example, it did not cause any because you did not hand in a line kwarg that may interfere with the function `y`.

Regarding the axes limit functionality: The two options `stretch` and `auto` are quite different from what I wanted to achieve. And their original intention is in the documentation. You may add the following sentence, but possibly it belongs to the documentation of `iplt.plot` (I hope it is correct, and not a special view point case - I am not at all an expert):

Using xlim/ylim set to `auto` together with disabling the autoscale feature of the corresponding axes `ax.autoscale(enable=False)` allows to preserve a user-defined zoom level while engaging the slider that modifies the line plot interactively.
