### ISSUE TITLE
Update supported Python versions

### ISSUE THREAD

**Issue by redeboer** [ianhi/mpl-interactions#184]
The list of supported Python versions is outdated.
https://github.com/ianhi/mpl-interactions/blob/b5b3b3d7db51c4dc6bb8e0e3c851ca13e8b2ec26/setup.py#L38-L43
This for instance has the following effect:
[![Supported Python versions](https://img.shields.io/pypi/pyversions/mpl-interactions)](https://pypi.org/project/mpl-interactions)

Some suggestions related to the setup:
- Use `setup.cfg`
- Use [setuptools-scm](https://pypi.org/project/setuptools-scm)
- Put `tests` under a different folder (`mpl_interactions/tests` is currently installed through pip as well)
- Put source code under `src` (see [pytest recommendation](https://docs.pytest.org/en/stable/goodpractices.html#tests-outside-application-code))
- Run pytest through GitHub Actions on all supported Python versions --> although... fair point 7f59c397
- Add above badge to README
- Add [`project_urls`](https://packaging.python.org/guides/distributing-packages-using-setuptools/#project-urls)

**Comment by ianhi** [comment]
> The list of supported Python versions is outdated.

Furthermore I think it's not even correct - I think I use `f` string formatting so this is probably `3.6+` only.

> Use setup.cfg

yup - i've learned a lot about python  packaging since I first made this.

> Use setuptools-scm

This still has a vibe of complexity to me - but I think I need to get over myself and just read how it works. So broadly yes - will does this work with doing releases via github actions?


> Put tests under a different folder (mpl_interactions/tests is currently installed through pip as well)

This was somewhat intentional because this is where matplotlib keeps them. I don't really have strong feelings here I suppose so im happy to move it.


> Run pytest through GitHub Actions on all supported Python versions --> although... fair point 7f59c39

:no_entry_sign: :fire: :earth_africa: 

> Add above badge to README
> Add project_urls

:+1:

**Comment by redeboer** [comment]
> This still has a vibe of complexity to me - but I think I need to get over myself and just read how it works. So broadly yes - will does this work with doing releases via github actions?

Yeah it's not really crucial. It also has the drawback that there is no version.py file, so I find that a bit magical sometimes. But indeed, it works perfectly with github actions (e.g. [here](https://github.com/ComPWA/tensorwaves/blob/06f9d51ca3138be416719efdef8ac8064dc00d20/.github/workflows/cd.yml#L24-L45)).

> This was somewhat intentional because this is where matplotlib keeps them. I don't really have strong feelings here I suppose so im happy to move it.

Interesting, they also have a `lib` folder, don't see that often in python codebases. But indeed, it also seems that matplotlib installs the tests (i.e. there is no exclude in the package find and the tests appear under site packages). I usually try to keep tests in the repo only (that's where you run pytest) and try to limit what files are installed, but I don't think there's a convention for this.

**Comment by ianhi** [comment]
> Interesting, they also have a lib folder, don't see that often in python codebases.

They have a bunch of `C++` and maybe `C` code which they keep under `src` so maybe that's why. But also bear in mind that matplotlib is very old released in 2003 it actually predates `git` so conventions may have changed in the past 18 years so they are perhaps not optimal for me to base decisions off of.
