### ISSUE TITLE
Strange display method in zoom/pan examples

### ISSUE THREAD

**Issue by houserockr** [ianhi/mpl-interactions#296]
The examples for panning and zooming mentioned here:
https://mpl-interactions.readthedocs.io/en/stable/examples/zoom-factory.html

use a strange `display()` method.

If I try to execute the code on these pages, I get

`NameError: name 'display' is not defined
`

My python version is 3.13.0

If I just remove this method, matplotlib will open and plot just fine. What is this for???

**Comment by Mian-Ahmed-Raza** [comment]
The error occurs because display() is not a built-in Python function but is instead part of the `IPython` library, which may not be imported in your environment. If you're running the code outside of a `Jupyter` Notebook or without importing the required modules, Python won't recognize display().

If you're running the code outside of a `Jupyter` Notebook (like in a regular Python script):

- You can safely remove the `display()` calls since they are not needed in standard scripts. As you mentioned, removing them doesn't affect the plotting or functionality of matplotlib.

If you're using a Jupyter Notebook or want to replicate this behavior:

You should import the `display()` function from the` IPython.display` module by adding this line at the beginning of your code:
`from IPython.display import display`

**Comment by houserockr** [comment]
Thank you very much, I've never used Jupyter before so I didn't know these cnoventions/interfaces.
I also had to install ipython first.

**Comment by Mian-Ahmed-Raza** [comment]
no problem feel free to ask if you have any issue further

**Comment by ianhi** [comment]
Thanks for answering @Mian-Ahmed-Raza 

Also @houserockr I'd like to add that you should instead use the [`mpl-pan-zoom`](https://mpl-pan-zoom.readthedocs.io/en/latest/) library for these functions, I plan to remove them from mpl-interactions in the future and only update them in that standaloen package.
